=== hub-se/PSP-UPPAAL/Tool/models/Rodrigues2018/flat-1_1.dtd
<!ELEMENT nta (imports?, declaration?, template+, instantiation?, system)>
<!ELEMENT imports (#PCDATA)>
<!ELEMENT declaration (#PCDATA)>
<!ELEMENT template (name, parameter?, declaration?, location*, init?, transition*)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name x   CDATA #IMPLIED
               y   CDATA #IMPLIED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter x   CDATA #IMPLIED
                    y   CDATA #IMPLIED>
<!ELEMENT location (name?, label*, urgent?, committed?)>
<!ATTLIST location id ID #REQUIRED
		   x  CDATA #IMPLIED
		   y  CDATA #IMPLIED
		   color CDATA #IMPLIED>
<!ELEMENT init EMPTY>
<!ATTLIST init ref IDREF #IMPLIED>
<!ELEMENT urgent EMPTY>
<!ELEMENT committed EMPTY>
<!ELEMENT transition (source, target, label*, nail*)>
<!ATTLIST transition id  ID #IMPLIED
                     x   CDATA #IMPLIED
                     y   CDATA #IMPLIED
		     color CDATA #IMPLIED>
<!ELEMENT source EMPTY>
<!ATTLIST source ref IDREF #REQUIRED>
<!ELEMENT target EMPTY>
<!ATTLIST target ref IDREF #REQUIRED>
<!ELEMENT label (#PCDATA)>
<!ATTLIST label	kind CDATA #REQUIRED
		x    CDATA #IMPLIED
		y    CDATA #IMPLIED>
<!ELEMENT nail EMPTY>
<!ATTLIST nail x   CDATA #REQUIRED
               y   CDATA #REQUIRED>
<!ELEMENT instantiation (#PCDATA)>
<!ELEMENT system (#PCDATA)>

=== hub-se/PSP-UPPAAL/Tool/models/complicatedTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'flat-1_1.dtd'>
<nta>
	<declaration>// Place global declarations here.</declaration>
	<template>
		<name x="5" y="5">Template</name>
		<declaration>// Place local declarations here.</declaration>
		<location id="id0" x="-25" y="-195">
		</location>
		<location id="id1" x="110" y="-42">
		</location>
		<location id="id2" x="-25" y="-136">
		</location>
		<location id="id3" x="110" y="-136">
			<name x="134" y="-128">wait</name>
		</location>
		<location id="id4" x="-204" y="178">
			<name x="-276" y="162">closing</name>
			<label kind="invariant" x="-260" y="178">x&lt;=6</label>
		</location>
		<location id="id5" x="-204" y="34">
			<name x="-180" y="18">closed</name>
			<label kind="invariant" x="-180" y="34">x&lt;=5</label>
		</location>
		<location id="id6" x="110" y="178">
			<name x="134" y="162">open</name>
			<label kind="invariant" x="134" y="178">x&lt;=8</label>
		</location>
		<location id="id7" x="110" y="34">
			<name x="134" y="18">opening</name>
			<label kind="invariant" x="134" y="34">x&lt;=6</label>
		</location>
		<location id="id8" x="-204" y="-136">
			<name x="-188" y="-128">idle</name>
		</location>
		<transition>
			<source ref="id0"/>
			<target ref="id2"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="17" y="-195">closed1!</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id7"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="110" y="-102">closed2?</label>
			<label kind="assignment" x="110" y="-76">x = 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id3"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-153" y="-170">pushed?</label>
			<label kind="assignment" x="-153" y="-153">activated = true</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-276" y="2">closed1!</label>
			<nail x="-244" y="58"/>
			<nail x="-244" y="34"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id8"/>
			<label kind="guard" x="-244" y="-80">x&gt;=5</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id5"/>
			<label kind="guard" x="-260" y="74">x==6</label>
			<label kind="assignment" x="-260" y="98">x=0,
activated=false</label>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id8"/>
			<label kind="synchronisation" x="-284" y="-168">closed1!</label>
			<nail x="-244" y="-112"/>
			<nail x="-244" y="-136"/>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id4"/>
			<label kind="guard" x="-45" y="154">x&gt;=4</label>
			<label kind="assignment" x="-37" y="186">x=0</label>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id6"/>
			<label kind="guard" x="118" y="74">x==6</label>
			<label kind="assignment" x="118" y="98">x=0</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = Template();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Recurrence_State_After_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan Q_reached, P_reached, P_left;
bool P_holds;
int t1;</declaration>
	<template>
		<name x="5" y="5">Recurrence_State_After_Timed</name>
		<declaration>// Place local declarations here.
clock c;</declaration>
		<location id="id0" x="-909" y="-348">
			<committed/>
		</location>
		<location id="id1" x="-1036" y="-348">
		</location>
		<location id="id2" x="-561" y="-459">
			<name x="-571" y="-493">ERROR</name>
		</location>
		<location id="id3" x="-561" y="-348">
		</location>
		<location id="id4" x="-739" y="-348">
			<label kind="invariant" x="-790" y="-374">c &lt;= t1</label>
		</location>
		<init ref="id1"/>
		<transition>
			<source ref="id1"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-1011" y="-365">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id4"/>
			<label kind="guard" x="-892" y="-365">P_holds == 0</label>
			<label kind="assignment" x="-892" y="-348">c = 0</label>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id3"/>
			<label kind="guard" x="-892" y="-263">P_holds == 1</label>
			<nail x="-909" y="-246"/>
			<nail x="-535" y="-246"/>
			<nail x="-535" y="-331"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id2"/>
			<label kind="guard" x="-705" y="-476">c &gt;= t1</label>
			<nail x="-739" y="-459"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-714" y="-323">P_left?</label>
			<label kind="assignment" x="-714" y="-306">c = 0</label>
			<nail x="-561" y="-306"/>
			<nail x="-739" y="-306"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-705" y="-365">P_reached?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Recurrence_State_After_Timed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Existence_State_After_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan Q_reached, P_reached;
bool Q_holds, P_holds;
int t1, t2;</declaration>
	<template>
		<name x="5" y="5">Existence_State_After_Timed</name>
		<declaration>// Place local declarations here.
clock c;</declaration>
		<location id="id0" x="195" y="212">
			<name x="212" y="204">ERROR</name>
		</location>
		<location id="id1" x="-76" y="119">
			<name x="-144" y="85">P_happens</name>
		</location>
		<location id="id2" x="85" y="212">
			<label kind="invariant" x="42" y="229">c &lt;= t2+1</label>
		</location>
		<location id="id3" x="-76" y="212">
			<committed/>
		</location>
		<location id="id4" x="-212" y="212">
			<name x="-246" y="178">SCOPEOPEN</name>
			<label kind="invariant" x="-238" y="229">c &lt;= t1</label>
		</location>
		<location id="id5" x="-357" y="212">
			<name x="-408" y="204">INIT</name>
		</location>
		<init ref="id5"/>
		<transition>
			<source ref="id2"/>
			<target ref="id0"/>
			<label kind="guard" x="110" y="195">c &gt;= t2</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="guard" x="-42" y="85">c &lt;= t2</label>
			<label kind="synchronisation" x="-42" y="102">P_reached?</label>
			<nail x="85" y="119"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="guard" x="-68" y="153">P_holds == 1</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="guard" x="-42" y="195">P_holds == 0</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="guard" x="-178" y="195">c == t1</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-339" y="195">Q_reached?</label>
			<label kind="assignment" x="-323" y="212">c = 0</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Existence_State_After_Timed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>Observer.SCOPEOPEN --&gt; Observer.P_happens
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>A[] Observer.INIT imply not $Q
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/PrecedenceChain1N_State_Globally_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan S_reached, P_reached, T1_reached, T2_reached, T3_reached;
bool T1_holds, T2_holds, T3_holds;</declaration>
	<template>
		<name x="5" y="5">PrecedenceChain_State_Globally_Untimed</name>
		<declaration>// Place local declarations here.
bool Z_Flag = 0;
bool P_Flag = 0;
</declaration>
		<location id="id0" x="-1929" y="-331">
			<committed/>
		</location>
		<location id="id1" x="-1929" y="-493">
			<name x="-1921" y="-527">INIT</name>
		</location>
		<location id="id2" x="-909" y="-493">
			<name x="-919" y="-527">END</name>
		</location>
		<location id="id3" x="-1037" y="-433">
		</location>
		<location id="id4" x="-1207" y="-493">
			<committed/>
		</location>
		<location id="id5" x="-1343" y="-433">
		</location>
		<location id="id6" x="-1521" y="-493">
			<committed/>
		</location>
		<location id="id7" x="-1648" y="-434">
		</location>
		<location id="id8" x="-1776" y="-493">
			<committed/>
		</location>
		<init ref="id1"/>
		<transition>
			<source ref="id0"/>
			<target ref="id1"/>
			<nail x="-1946" y="-476"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-1929" y="-429">P_reached?</label>
			<label kind="assignment" x="-1929" y="-412">P_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id8"/>
			<label kind="synchronisation" x="-1895" y="-510">S_reached?</label>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id6"/>
			<label kind="synchronisation" x="-1630" y="-450">T1_reached?</label>
			<nail x="-1521" y="-433"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id7"/>
			<label kind="guard" x="-1768" y="-450">T1_holds == 0</label>
			<nail x="-1776" y="-433"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-1019" y="-450">T3_reached?</label>
			<nail x="-909" y="-433"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="guard" x="-1182" y="-450">T3_holds == 0</label>
			<nail x="-1190" y="-433"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-1325" y="-450">T2_reached?</label>
			<nail x="-1207" y="-433"/>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id5"/>
			<label kind="guard" x="-1487" y="-450">T2_holds == 0</label>
			<nail x="-1504" y="-433"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id2"/>
			<label kind="guard" x="-1182" y="-510">T3_holds == 1</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id4"/>
			<label kind="guard" x="-1487" y="-510">T2_holds == 1</label>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id6"/>
			<label kind="guard" x="-1759" y="-510">T1_holds == 1</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = PrecedenceChain_State_Globally_Untimed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
		<query>
			<formula>START --&gt; GOAL
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/ResponseConstrained_State_Globally_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan P_entered, S_entered;</declaration>
	<template>
		<name x="5" y="5">ResponseConstrained_State_Globally_Untimed</name>
		<declaration>// Place local declarations here.</declaration>
		<location id="id0" x="170" y="-8">
			<name x="160" y="-42">P_happens</name>
		</location>
		<location id="id1" x="0" y="-8">
			<name x="-10" y="-42">S_happens</name>
		</location>
		<init ref="id1"/>
		<transition>
			<source ref="id0"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="59" y="76">S_entered?</label>
			<nail x="93" y="76"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="18" y="-25">P_entered?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = ResponseConstrained_State_Globally_Untimed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
		<query>
			<formula>P_happens--&gt;S_happens
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Recurrence_State_Between_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, Q_reached, P_entered, P_left;
bool R_holds;
bool P_holds;</declaration>
	<template>
		<name x="5" y="5">Recurrence_State_Between_Untimed</name>
		<declaration>// Place local declarations here.
</declaration>
		<location id="id0" x="-5432" y="-5627">
			<committed/>
		</location>
		<location id="id1" x="-5279" y="-5627">
		</location>
		<location id="id2" x="-5576" y="-5627">
			<name x="-5602" y="-5661">INIT</name>
		</location>
		<location id="id3" x="-5151" y="-5627">
			<name x="-5143" y="-5661">VALIDATION</name>
			<committed/>
		</location>
		<init ref="id2"/>
		<transition>
			<source ref="id0"/>
			<target ref="id2"/>
			<label kind="guard" x="-5550" y="-5610">R_holds == 1</label>
			<nail x="-5432" y="-5593"/>
			<nail x="-5576" y="-5593"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id1"/>
			<label kind="guard" x="-5406" y="-5644">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-5550" y="-5644">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-5261" y="-5644">R_reached?</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<nail x="-5151" y="-5695"/>
			<nail x="-5601" y="-5695"/>
			<nail x="-5601" y="-5635"/>
			<nail x="-5601" y="-5635"/>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Recurrence_State_Between_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] Observer.VALIDATION imply $P_holds
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/ResponseChainConstrained1N_State_Before_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, Z0_reached, Z1_reached, Z2_reached, Z3_reached, T1_reached, T2_reached, T3_reached, S_reached, P_reached;
bool T1_holds, T2_holds, T3_holds, Z0_holds, Z1_holds, Z2_holds, Z3_holds, S_holds;</declaration>
	<template>
		<name x="5" y="5">ResponseChainConstrained1N_State_Before_Timed</name>
		<declaration>// Place local declarations here.
clock c;
bool Z_Flag = 0;
int t0 = 1;
int t1 = 2;
int t2 = 3;
int t3 = 4;</declaration>
		<location id="id0" x="688" y="-127">
			<name x="654" y="-161">EVALUATE</name>
			<committed/>
		</location>
		<location id="id1" x="-781" y="102">
			<name x="-849" y="93">ERROR</name>
		</location>
		<location id="id2" x="425" y="-59">
		</location>
		<location id="id3" x="128" y="-59">
		</location>
		<location id="id4" x="-169" y="-59">
		</location>
		<location id="id5" x="-509" y="-59">
		</location>
		<location id="id6" x="569" y="-127">
			<name x="559" y="-161">END</name>
		</location>
		<location id="id7" x="247" y="-127">
			<committed/>
		</location>
		<location id="id8" x="-25" y="-127">
			<committed/>
		</location>
		<location id="id9" x="-382" y="-127">
			<committed/>
		</location>
		<location id="id10" x="-628" y="-127">
			<committed/>
		</location>
		<location id="id11" x="-747" y="-127">
		</location>
		<init ref="id11"/>
		<transition>
			<source ref="id6"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="586" y="-144">R_reached?</label>
			<nail x="586" y="-127"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="213" y="51">R_reached?</label>
			<nail x="255" y="102"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-51" y="51">R_reached?</label>
			<nail x="9" y="102"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-407" y="42">R_reached?</label>
			<nail x="-373" y="102"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-781" y="34">R_reached?</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="399" y="8">Z3_reached?</label>
			<label kind="assignment" x="399" y="25">Z_Flag = 1</label>
			<nail x="399" y="0"/>
			<nail x="425" y="0"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id6"/>
			<label kind="guard" x="442" y="-59">c &lt; t3</label>
			<label kind="synchronisation" x="443" y="-76">T3_reached?</label>
			<nail x="569" y="-59"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id2"/>
			<label kind="guard" x="255" y="-42">T1_holds == 0 &amp;&amp;
Z1_holds == 1</label>
			<label kind="assignment" x="255" y="-8">Z_Flag = 1</label>
			<nail x="264" y="-51"/>
			<nail x="391" y="-51"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id2"/>
			<label kind="guard" x="298" y="-127">T3_holds == 0 &amp;&amp;
Z3_holds == 0</label>
			<nail x="272" y="-102"/>
			<nail x="399" y="-59"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id7"/>
			<label kind="guard" x="144" y="-59">c &lt; t2</label>
			<label kind="synchronisation" x="146" y="-76">T2_reached?</label>
			<nail x="247" y="-59"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="111" y="8">Z2_reached?</label>
			<label kind="assignment" x="111" y="25">Z_Flag = 1</label>
			<nail x="102" y="0"/>
			<nail x="128" y="0"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id3"/>
			<label kind="guard" x="-25" y="-34">T2_holds == 0 &amp;&amp;
Z2_holds == 1</label>
			<label kind="assignment" x="-8" y="8">Z_Flag = 1</label>
			<nail x="-17" y="-34"/>
			<nail x="102" y="-34"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id3"/>
			<label kind="guard" x="43" y="-127">T2_holds == 0 &amp;&amp;
Z2_holds == 0</label>
			<nail x="102" y="-59"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-195" y="8">Z1_reached?</label>
			<label kind="assignment" x="-195" y="25">Z_Flag = 1</label>
			<nail x="-195" y="0"/>
			<nail x="-169" y="0"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id8"/>
			<label kind="guard" x="-144" y="-59">c &lt; t1</label>
			<label kind="synchronisation" x="-144" y="-76">T1_reached?</label>
			<nail x="-25" y="-59"/>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id4"/>
			<label kind="guard" x="-365" y="-51">T1_holds == 0 &amp;&amp;
Z1_holds == 1</label>
			<label kind="assignment" x="-365" y="-17">Z_Flag = 1</label>
			<nail x="-365" y="-59"/>
			<nail x="-212" y="-59"/>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id4"/>
			<label kind="guard" x="-322" y="-127">T1_holds == 0 &amp;&amp;
Z1_holds == 0</label>
			<nail x="-365" y="-110"/>
			<nail x="-203" y="-59"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id9"/>
			<label kind="guard" x="-467" y="-59">c &lt; t0</label>
			<label kind="synchronisation" x="-467" y="-76">S_reached?</label>
			<nail x="-382" y="-59"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-518" y="8">Z0_reached?</label>
			<label kind="assignment" x="-518" y="25">Z_Flag = 1</label>
			<nail x="-535" y="0"/>
			<nail x="-509" y="0"/>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id5"/>
			<label kind="guard" x="-705" y="-59">S_holds == 0 &amp;&amp;
Z0_holds == 1</label>
			<label kind="assignment" x="-705" y="-25">Z_Flag = 1</label>
			<nail x="-679" y="-59"/>
			<nail x="-569" y="-59"/>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id5"/>
			<label kind="guard" x="-594" y="-119">S_holds == 0 &amp;&amp;
Z0_holds == 0</label>
			<nail x="-569" y="-59"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id6"/>
			<label kind="guard" x="331" y="-144">T3_holds == 1</label>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id7"/>
			<label kind="guard" x="43" y="-144">T2_holds == 1</label>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id8"/>
			<label kind="guard" x="-305" y="-144">T1_holds == 1</label>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id9"/>
			<label kind="guard" x="-552" y="-144">S_holds == 1</label>
		</transition>
		<transition>
			<source ref="id11"/>
			<target ref="id10"/>
			<label kind="synchronisation" x="-729" y="-144">P_reached?</label>
			<label kind="assignment" x="-729" y="-127">c = 0</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = ResponseChainConstrained1N_State_Before_Timed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Existence_State_Until_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.

broadcast chan Q_reached, R_reached, P_reached;
bool R_holds, P_holds;</declaration>
	<template>
		<name x="5" y="5">Existence_State_Until_Untimed</name>
		<declaration>// Place local declarations here.</declaration>
		<location id="id0" x="-425" y="-187">
			<committed/>
		</location>
		<location id="id1" x="-289" y="-306">
			<name x="-306" y="-348">FULFILLED</name>
		</location>
		<location id="id2" x="-17" y="-187">
			<name x="-26" y="-170">ERROR</name>
		</location>
		<location id="id3" x="-153" y="-187">
		</location>
		<location id="id4" x="-289" y="-187">
			<name x="-289" y="-170">SCOPEOPEN</name>
			<committed/>
		</location>
		<location id="id5" x="-578" y="-187">
			<name x="-620" y="-187">INIT</name>
		</location>
		<init ref="id5"/>
		<transition>
			<source ref="id0"/>
			<target ref="id5"/>
			<label kind="guard" x="-544" y="-161">R_holds ==1</label>
			<nail x="-442" y="-144"/>
			<nail x="-552" y="-144"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id4"/>
			<label kind="guard" x="-408" y="-204">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-560" y="-204">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-263" y="-331">P_reached?</label>
			<nail x="-153" y="-306"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-552" y="-323">R_reached?</label>
			<nail x="-578" y="-306"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id1"/>
			<label kind="guard" x="-391" y="-280">P_holds == 1</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-127" y="-212">R_reached?</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="guard" x="-272" y="-212">P_holds == 0</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-484" y="-127">R_reached?</label>
			<nail x="-306" y="-110"/>
			<nail x="-561" y="-110"/>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Existence_State_Until_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] Observer.INIT imply not $Q
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>SCOPEOPEN --&gt; FULFILLED
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>
