=== hub-se/PSP-UPPAAL/Tool/models/Rodrigues2018/flat-1_1.dtd
<!ELEMENT nta (imports?, declaration?, template+, instantiation?, system)>
<!ELEMENT imports (#PCDATA)>
<!ELEMENT declaration (#PCDATA)>
<!ELEMENT template (name, parameter?, declaration?, location*, init?, transition*)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name x   CDATA #IMPLIED
               y   CDATA #IMPLIED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter x   CDATA #IMPLIED
                    y   CDATA #IMPLIED>
<!ELEMENT location (name?, label*, urgent?, committed?)>
<!ATTLIST location id ID #REQUIRED
		   x  CDATA #IMPLIED
		   y  CDATA #IMPLIED
		   color CDATA #IMPLIED>
<!ELEMENT init EMPTY>
<!ATTLIST init ref IDREF #IMPLIED>
<!ELEMENT urgent EMPTY>
<!ELEMENT committed EMPTY>
<!ELEMENT transition (source, target, label*, nail*)>
<!ATTLIST transition id  ID #IMPLIED
                     x   CDATA #IMPLIED
                     y   CDATA #IMPLIED
		     color CDATA #IMPLIED>
<!ELEMENT source EMPTY>
<!ATTLIST source ref IDREF #REQUIRED>
<!ELEMENT target EMPTY>
<!ATTLIST target ref IDREF #REQUIRED>
<!ELEMENT label (#PCDATA)>
<!ATTLIST label	kind CDATA #REQUIRED
		x    CDATA #IMPLIED
		y    CDATA #IMPLIED>
<!ELEMENT nail EMPTY>
<!ATTLIST nail x   CDATA #REQUIRED
               y   CDATA #REQUIRED>
<!ELEMENT instantiation (#PCDATA)>
<!ELEMENT system (#PCDATA)>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/BoundedExistence_State_Globally_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan P_reached, P_left;
bool P_holds;
int n_;
bool nxtCmt = 1;</declaration>
	<template>
		<name x="5" y="5">BoundedExistence_State_Globally_Untimed</name>
		<declaration>// Place local declarations here.
int counter = 0;</declaration>
		<location id="id0" x="195" y="-204">
			<name x="170" y="-187">ERROR</name>
		</location>
		<location id="id1" x="17" y="-204">
			<committed/>
		</location>
		<location id="id2" x="-408" y="-102">
			<committed/>
		</location>
		<location id="id3" x="-170" y="-204">
		</location>
		<location id="id4" x="-170" y="-102">
		</location>
		<location id="id5" x="-535" y="-102">
			<name x="-545" y="-136">INIT</name>
			<committed/>
		</location>
		<init ref="id5"/>
		<transition>
			<source ref="id1"/>
			<target ref="id0"/>
			<label kind="guard" x="51" y="-229">counter &gt; n_</label>
			<label kind="assignment" x="51" y="-204">nxtCmt=0</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="guard" x="-119" y="-229">counter &lt;= n_</label>
			<label kind="assignment" x="-119" y="-204">nxtCmt=0</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-102" y="-136">P_reached?</label>
			<label kind="assignment" x="-136" y="-119">counter = counter+1,
nxtCmt=1</label>
			<nail x="17" y="-102"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id3"/>
			<label kind="guard" x="-348" y="-238">P_holds == 1</label>
			<label kind="assignment" x="-374" y="-221">counter = counter+1,
nxtCmt=0</label>
			<nail x="-408" y="-204"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id4"/>
			<label kind="guard" x="-340" y="-127">P_holds == 0</label>
			<label kind="assignment" x="-348" y="-102">nxtCmt=0</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id2"/>
			<label kind="assignment" x="-518" y="-119">counter = 0</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-161" y="-170">P_left?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = BoundedExistence_State_Globally_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/MaximumDuration_State_Before_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan P_reached, P_left, R_reached;
int t2;</declaration>
	<template>
		<name x="5" y="5">MaximumDuration_State_Before_Timed</name>
		<declaration>// Place local declarations here.
clock c;
</declaration>
		<location id="id0" x="-161" y="-93">
		</location>
		<location id="id1" x="119" y="-178">
			<name x="109" y="-212">ERROR</name>
		</location>
		<location id="id2" x="-17" y="-178">
		</location>
		<location id="id3" x="-161" y="-178">
			<label kind="invariant" x="-178" y="-161">c &lt;= t1</label>
		</location>
		<location id="id4" x="-289" y="-178">
		</location>
		<init ref="id4"/>
		<transition>
			<source ref="id4"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-280" y="-110">R_reached?</label>
			<nail x="-289" y="-93"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-255" y="-153">P_left?</label>
			<nail x="-187" y="-153"/>
			<nail x="-263" y="-153"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="1" y="-195">R_reached?</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-68" y="-161">R_reached?</label>
			<nail x="-127" y="-161"/>
			<nail x="102" y="-161"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-187" y="-272">P_reached?</label>
			<label kind="assignment" x="-178" y="-246">c = 0</label>
			<nail x="-187" y="-195"/>
			<nail x="-187" y="-246"/>
			<nail x="-127" y="-246"/>
			<nail x="-127" y="-195"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="guard" x="-119" y="-195">c &gt;= t1</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-271" y="-195">P_reached?</label>
			<label kind="assignment" x="-271" y="-178">c = 0</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = MaximumDuration_State_Before_Timed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Response_State_Globally_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'flat-1_1.dtd'>
<nta>
	<declaration>// Place global declarations here.
broadcast chan P_reached, S_reached;
int t1, t2;</declaration>
	<template>
		<name x="5" y="5">Response_State_Globally_Timed</name>
		<declaration>// Place local declarations here.
clock c;</declaration>
		<location id="id0" x="-620" y="-331">
		</location>
		<location id="id1" x="-374" y="-331">
			<name x="-384" y="-314">ERROR</name>
		</location>
		<location id="id2" x="-484" y="-331">
			<name x="-493" y="-314">wait</name>
		</location>
		<init ref="id0"/>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="guard" x="-450" y="-348">c &gt; t2</label>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-595" y="-348">P_reached?</label>
			<label kind="assignment" x="-578" y="-331">c = 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id0"/>
			<label kind="guard" x="-620" y="-416">c &gt;= t1 &amp;&amp; c &lt;= t2</label>
			<label kind="synchronisation" x="-595" y="-399">S_reached?</label>
			<nail x="-484" y="-382"/>
			<nail x="-620" y="-382"/>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Response_State_Globally_Timed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Response_State_Before_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, S_reached, P_reached;</declaration>
	<template>
		<name x="5" y="5">Response_State_Before_Untimed</name>
		<location id="id0" x="110" y="-178">
			<name x="100" y="-212">ERROR</name>
		</location>
		<location id="id1" x="-195" y="-68">
		</location>
		<location id="id2" x="-25" y="-178">
		</location>
		<location id="id3" x="-195" y="-178">
			<name x="-205" y="-212">INIT</name>
		</location>
		<init ref="id3"/>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-187" y="-110">R_reached?</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="0" y="-195">R_reached?</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-144" y="-153">S_reached?</label>
			<nail x="-51" y="-136"/>
			<nail x="-161" y="-136"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-144" y="-195">P_reached?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Response_State_Before_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/ResponseInvariance_Between_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, Q_reached, P_reached, S_left;
bool S_holds, R_holds;</declaration>
	<template>
		<name x="5" y="5">ResponseInvariance_State_Between_Timed</name>
		<declaration>// Place local declarations here.
clock c;
int l = 3;
int u = 5;</declaration>
		<location id="id0" x="-442" y="-221">
			<committed/>
		</location>
		<location id="id1" x="-187" y="-221">
			<label kind="invariant" x="-204" y="-204">c &lt;= l</label>
		</location>
		<location id="id2" x="204" y="-85">
			<name x="187" y="-119">ERROR</name>
		</location>
		<location id="id3" x="-586" y="-221">
		</location>
		<location id="id4" x="51" y="-85">
		</location>
		<location id="id5" x="51" y="-221">
		</location>
		<location id="id6" x="-76" y="-221">
			<committed/>
		</location>
		<location id="id7" x="-297" y="-221">
		</location>
		<init ref="id3"/>
		<transition>
			<source ref="id0"/>
			<target ref="id3"/>
			<label kind="guard" x="-544" y="-195">R_holds == 1</label>
			<nail x="-451" y="-195"/>
			<nail x="-561" y="-195"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id7"/>
			<label kind="guard" x="-416" y="-238">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-568" y="-238">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id6"/>
			<label kind="guard" x="-161" y="-246">c == l</label>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-279" y="-238">P_reached?</label>
			<label kind="assignment" x="-279" y="-221">c = 0</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id3"/>
			<label kind="guard" x="-568" y="-433">c &gt; u</label>
			<label kind="synchronisation" x="-568" y="-416">R_reached?</label>
			<nail x="51" y="-399"/>
			<nail x="-586" y="-399"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="85" y="-102">R_reached?</label>
			<label kind="comments" x="69" y="-60">Not sure about this transition, but what else would be the difference between 'UNTIL' and 'BETWEEN'?</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id3"/>
			<label kind="guard" x="-568" y="-340">c &lt; l</label>
			<label kind="synchronisation" x="-568" y="-323">R_reached?</label>
			<nail x="51" y="-306"/>
			<nail x="-586" y="-306"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-416" y="-144">R_reached?</label>
			<nail x="-297" y="-144"/>
			<nail x="-586" y="-144"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="guard" x="51" y="-187">c &lt; u &amp;&amp; c &gt; l</label>
			<label kind="synchronisation" x="51" y="-170">S_left?</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id4"/>
			<label kind="guard" x="-85" y="-136">S_holds == 0</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id5"/>
			<label kind="guard" x="-59" y="-246">S_holds == 1</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = ResponseInvariance_State_Between_Timed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Universality_State_Until_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>broadcast chan Q_reached, R_reached;
broadcast chan P_left;
bool R_holds;
int t1, t2;</declaration>
	<template>
		<name x="5" y="5">Universality_State_Until_Timed</name>
		<declaration>clock c;</declaration>
		<location id="id0" x="-510" y="-221">
			<committed/>
		</location>
		<location id="id1" x="-195" y="-221">
			<name x="-221" y="-204">ERROR</name>
		</location>
		<location id="id2" x="-349" y="-221">
			<name x="-399" y="-255">SCOPEOPEN</name>
		</location>
		<location id="id3" x="-671" y="-221">
			<name x="-714" y="-212">INIT</name>
		</location>
		<init ref="id3"/>
		<transition>
			<source ref="id0"/>
			<target ref="id3"/>
			<label kind="guard" x="-654" y="-289">R_holds == 1</label>
			<nail x="-510" y="-272"/>
			<nail x="-671" y="-272"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id2"/>
			<label kind="guard" x="-493" y="-238">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-653" y="-238">Q_reached?</label>
			<label kind="assignment" x="-653" y="-221">c = 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-645" y="-161">R_reached?</label>
			<nail x="-348" y="-161"/>
			<nail x="-671" y="-161"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="guard" x="-306" y="-263">c &gt;= t1 and c &lt;= t2</label>
			<label kind="synchronisation" x="-297" y="-246">P_left?</label>
		</transition>
	</template>
	<system>
Observer = Universality_State_Until_Timed();
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] (Observer.SCOPEOPEN and Observer.c == $t1) imply $P
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>A[] Observer.INIT imply not $Q
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/PrecedenceChain1N_State_Before_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, S_reached, T1_reached, T2_reached, T3_reached, P_reached;
bool T1_holds, T2_holds, T3_holds;</declaration>
	<template>
		<name x="5" y="5">PrecedenceChain_State_Before_Untimed</name>
		<declaration>// Place local declarations here.
bool Z_Flag = 0;
bool P_Flag = 0;
bool R_Flag = 0;
</declaration>
		<location id="id0" x="-782" y="-493">
			<name x="-792" y="-527">EVALUATE</name>
		</location>
		<location id="id1" x="-960" y="-340">
			<committed/>
		</location>
		<location id="id2" x="-1292" y="-340">
			<committed/>
		</location>
		<location id="id3" x="-1581" y="-331">
			<committed/>
		</location>
		<location id="id4" x="-1997" y="-331">
			<committed/>
		</location>
		<location id="id5" x="-1929" y="-331">
			<committed/>
		</location>
		<location id="id6" x="-1929" y="-493">
			<name x="-1921" y="-527">INIT</name>
		</location>
		<location id="id7" x="-909" y="-493">
			<name x="-919" y="-527">END</name>
		</location>
		<location id="id8" x="-1037" y="-433">
		</location>
		<location id="id9" x="-1207" y="-493">
			<committed/>
		</location>
		<location id="id10" x="-1343" y="-433">
		</location>
		<location id="id11" x="-1521" y="-493">
			<committed/>
		</location>
		<location id="id12" x="-1648" y="-434">
		</location>
		<location id="id13" x="-1776" y="-493">
			<committed/>
		</location>
		<init ref="id6"/>
		<transition>
			<source ref="id7"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-891" y="-510">R_reached?</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id8"/>
			<nail x="-1003" y="-340"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-977" y="-399">R_reached?</label>
			<label kind="assignment" x="-977" y="-382">R_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id10"/>
			<nail x="-1317" y="-340"/>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-1300" y="-399">R_reached?</label>
			<label kind="assignment" x="-1300" y="-382">R_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id12"/>
			<nail x="-1615" y="-331"/>
		</transition>
		<transition>
			<source ref="id12"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-1606" y="-399">R_reached?</label>
			<label kind="assignment" x="-1606" y="-382">R_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id6"/>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-2057" y="-459">R_reached?</label>
			<label kind="assignment" x="-2057" y="-442">R_Flag = 1</label>
			<nail x="-1955" y="-476"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id6"/>
			<nail x="-1938" y="-459"/>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-1929" y="-429">P_reached?</label>
			<label kind="assignment" x="-1929" y="-412">P_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id13"/>
			<label kind="synchronisation" x="-1895" y="-510">S_reached?</label>
		</transition>
		<transition>
			<source ref="id12"/>
			<target ref="id11"/>
			<label kind="synchronisation" x="-1630" y="-450">T1_reached?</label>
			<nail x="-1521" y="-433"/>
		</transition>
		<transition>
			<source ref="id13"/>
			<target ref="id12"/>
			<label kind="guard" x="-1768" y="-450">T1_holds == 0</label>
			<nail x="-1776" y="-433"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id7"/>
			<label kind="synchronisation" x="-1019" y="-450">T3_reached?</label>
			<nail x="-909" y="-433"/>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id8"/>
			<label kind="guard" x="-1182" y="-450">T3_holds == 0</label>
			<nail x="-1190" y="-433"/>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id9"/>
			<label kind="synchronisation" x="-1325" y="-450">T2_reached?</label>
			<nail x="-1207" y="-433"/>
		</transition>
		<transition>
			<source ref="id11"/>
			<target ref="id10"/>
			<label kind="guard" x="-1487" y="-450">T2_holds == 0</label>
			<nail x="-1504" y="-433"/>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id7"/>
			<label kind="guard" x="-1182" y="-510">T3_holds == 1</label>
		</transition>
		<transition>
			<source ref="id11"/>
			<target ref="id9"/>
			<label kind="guard" x="-1487" y="-510">T2_holds == 1</label>
		</transition>
		<transition>
			<source ref="id13"/>
			<target ref="id11"/>
			<label kind="guard" x="-1759" y="-510">T1_holds == 1</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = PrecedenceChain_State_Before_Untimed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
		<query>
			<formula>START --&gt; GOAL
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/PrecedenceChain_State_Between_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, S_entered, P_entered, T_entered, Q_reached;
bool R_holds, P_holds, S_holds, T_holds;</declaration>
	<template>
		<name x="5" y="5">PrecedenceChain2_State_Between_Untimed</name>
		<declaration>// Place local declarations here.
clock c;</declaration>
		<location id="id0" x="-1054" y="-1232">
			<name x="-1054" y="-1215">ERROR</name>
		</location>
		<location id="id1" x="-1292" y="-1445">
		</location>
		<location id="id2" x="-901" y="-1419">
		</location>
		<location id="id3" x="-1292" y="-1530">
			<committed/>
		</location>
		<location id="id4" x="-1054" y="-1419">
			<committed/>
		</location>
		<location id="id5" x="-1054" y="-1530">
			<committed/>
		</location>
		<location id="id6" x="-1445" y="-1530">
			<committed/>
		</location>
		<location id="id7" x="-1555" y="-1530">
		</location>
		<location id="id8" x="-1054" y="-1309">
			<name x="-1156" y="-1292">MayBeERROR</name>
		</location>
		<location id="id9" x="-765" y="-1530">
			<name x="-756" y="-1555">T_Holds</name>
		</location>
		<init ref="id7"/>
		<transition>
			<source ref="id8"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-1054" y="-1287">R_reached?</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id8"/>
			<label kind="synchronisation" x="-1274" y="-1351">P_entered?</label>
			<nail x="-1292" y="-1334"/>
			<nail x="-1079" y="-1334"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-1266" y="-1462">S_entered?</label>
			<nail x="-1071" y="-1445"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id7"/>
			<label kind="synchronisation" x="-1538" y="-1462">R_reached?</label>
			<nail x="-1555" y="-1445"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="guard" x="-1292" y="-1504">S_holds == 0 &amp;&amp;
P_holds == 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id7"/>
			<label kind="synchronisation" x="-1538" y="-1683">R_reached?</label>
			<nail x="-875" y="-1402"/>
			<nail x="-646" y="-1402"/>
			<nail x="-646" y="-1666"/>
			<nail x="-1589" y="-1666"/>
			<nail x="-1589" y="-1530"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id8"/>
			<label kind="synchronisation" x="-1020" y="-1334">P_entered?</label>
			<nail x="-901" y="-1309"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id9"/>
			<label kind="synchronisation" x="-867" y="-1445">T_entered?</label>
			<nail x="-765" y="-1419"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id2"/>
			<label kind="guard" x="-1029" y="-1445">P_holds == 0</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id8"/>
			<label kind="guard" x="-1148" y="-1394">P_holds == 1</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id8"/>
			<label kind="guard" x="-1445" y="-1343">P_holds == 1 &amp;&amp;
S_holds == 0</label>
			<nail x="-1326" y="-1496"/>
			<nail x="-1326" y="-1309"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id5"/>
			<label kind="guard" x="-1266" y="-1555">S_holds == 1</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id7"/>
			<label kind="synchronisation" x="-1538" y="-1589">R_reached?</label>
			<nail x="-1326" y="-1572"/>
			<nail x="-1547" y="-1572"/>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id3"/>
			<label kind="guard" x="-1415" y="-1530">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id9"/>
			<label kind="guard" x="-884" y="-1555">T_holds == 1</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="guard" x="-1054" y="-1496">T_holds == 0</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id7"/>
			<label kind="guard" x="-1538" y="-1496">R_holds == 1</label>
			<nail x="-1453" y="-1496"/>
			<nail x="-1547" y="-1496"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id6"/>
			<label kind="synchronisation" x="-1537" y="-1547">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id7"/>
			<label kind="synchronisation" x="-1538" y="-1640">R_reached?</label>
			<nail x="-765" y="-1624"/>
			<nail x="-1555" y="-1623"/>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = PrecedenceChain2_State_Between_Untimed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
	</queries>
</nta>
