=== hub-se/PSP-UPPAAL/Tool/models/Rodrigues2018/flat-1_1.dtd
<!ELEMENT nta (imports?, declaration?, template+, instantiation?, system)>
<!ELEMENT imports (#PCDATA)>
<!ELEMENT declaration (#PCDATA)>
<!ELEMENT template (name, parameter?, declaration?, location*, init?, transition*)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name x   CDATA #IMPLIED
               y   CDATA #IMPLIED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter x   CDATA #IMPLIED
                    y   CDATA #IMPLIED>
<!ELEMENT location (name?, label*, urgent?, committed?)>
<!ATTLIST location id ID #REQUIRED
		   x  CDATA #IMPLIED
		   y  CDATA #IMPLIED
		   color CDATA #IMPLIED>
<!ELEMENT init EMPTY>
<!ATTLIST init ref IDREF #IMPLIED>
<!ELEMENT urgent EMPTY>
<!ELEMENT committed EMPTY>
<!ELEMENT transition (source, target, label*, nail*)>
<!ATTLIST transition id  ID #IMPLIED
                     x   CDATA #IMPLIED
                     y   CDATA #IMPLIED
		     color CDATA #IMPLIED>
<!ELEMENT source EMPTY>
<!ATTLIST source ref IDREF #REQUIRED>
<!ELEMENT target EMPTY>
<!ATTLIST target ref IDREF #REQUIRED>
<!ELEMENT label (#PCDATA)>
<!ATTLIST label	kind CDATA #REQUIRED
		x    CDATA #IMPLIED
		y    CDATA #IMPLIED>
<!ELEMENT nail EMPTY>
<!ATTLIST nail x   CDATA #REQUIRED
               y   CDATA #REQUIRED>
<!ELEMENT instantiation (#PCDATA)>
<!ELEMENT system (#PCDATA)>

=== hub-se/PSP-UPPAAL/observer_templates/ResponseConstrained_State_Between_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan Q_reached, R_reached, P_entered, S_entered, ZS_reached;
bool R_holds;</declaration>
	<template>
		<name x="5" y="5">ResponseConstrained_State_Between_Untimed</name>
		<declaration>// Place local declarations here.
clock c;
int l = 3;
int u = 5;</declaration>
		<location id="id0" x="85" y="-144">
		</location>
		<location id="id1" x="-340" y="-178">
			<committed/>
		</location>
		<location id="id2" x="204" y="-178">
			<name x="194" y="-212">ERROR</name>
		</location>
		<location id="id3" x="-476" y="-178">
		</location>
		<location id="id4" x="-25" y="-178">
		</location>
		<location id="id5" x="-195" y="-178">
		</location>
		<init ref="id3"/>
		<transition>
			<source ref="id0"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="103" y="-161">R_reached?</label>
			<nail x="204" y="-144"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-17" y="-161">ZS_reached?</label>
			<nail x="-25" y="-144"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="guard" x="-459" y="-153">R_holds == 1</label>
			<nail x="-357" y="-153"/>
			<nail x="-459" y="-153"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id5"/>
			<label kind="guard" x="-314" y="-195">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-458" y="-195">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-459" y="-85">R_reached?</label>
			<nail x="-195" y="-93"/>
			<nail x="-476" y="-93"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="42" y="-195">R_reached?</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id5"/>
			<label kind="synchronisation" x="-136" y="-94">S_entered?</label>
			<nail x="-102" y="-94"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-177" y="-195">P_entered?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = ResponseConstrained_State_Between_Untimed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/Universality_State_Until_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
bool R_holds, P_holds;
broadcast chan Q_reached, R_reached, P_reached, P_left;
bool nxtCmt = 0;</declaration>
	<template>
		<name x="5" y="5">Universality_State_Until_Untimed</name>
		<declaration>// Place local declarations here.</declaration>
		<location id="id0" x="-450" y="-187">
			<committed/>
		</location>
		<location id="id1" x="-289" y="-272">
		</location>
		<location id="id2" x="-153" y="-187">
			<name x="-178" y="-170">ERROR</name>
		</location>
		<location id="id3" x="-289" y="-187">
			<committed/>
		</location>
		<location id="id4" x="-578" y="-187">
			<name x="-620" y="-212">INIT</name>
		</location>
		<init ref="id4"/>
		<transition>
			<source ref="id0"/>
			<target ref="id4"/>
			<label kind="guard" x="-561" y="-170">R_holds == 1</label>
			<label kind="assignment" x="-551" y="-153">nxtCmt = 0</label>
			<nail x="-458" y="-153"/>
			<nail x="-569" y="-153"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id3"/>
			<label kind="guard" x="-425" y="-212">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-560" y="-204">Q_reached?</label>
			<label kind="assignment" x="-560" y="-187">nxtCmt = 1</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-263" y="-298">P_left?</label>
			<nail x="-153" y="-272"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-450" y="-298">R_reached?</label>
			<nail x="-578" y="-272"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id1"/>
			<label kind="guard" x="-391" y="-255">P_holds == 1</label>
			<label kind="assignment" x="-374" y="-238">nxtCmt = 0</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="guard" x="-272" y="-212">P_holds == 0</label>
			<label kind="assignment" x="-271" y="-187">nxtCmt = 0</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-399" y="-136">R_reached?</label>
			<label kind="assignment" x="-399" y="-119">nxtCmt = 0</label>
			<nail x="-289" y="-136"/>
			<nail x="-578" y="-136"/>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Universality_State_Until_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>A[] Observer.INIT imply not $Q
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/MaximumDuration_State_Globally_Timed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan P_reached;</declaration>
	<template>
		<name x="5" y="5">MaximumDuration_State_Globally_Timed</name>
		<declaration>// Place local declarations here.
clock c;</declaration>
		<location id="id0" x="-408" y="-170">
		</location>
		<location id="id1" x="-272" y="-170">
			<name x="-255" y="-178">Scope</name>
		</location>
		<init ref="id0"/>
		<transition>
			<source ref="id0"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-382" y="-187">P_reached?</label>
			<label kind="assignment" x="-382" y="-170">c = 0</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-263" y="-229">P_reached?</label>
			<label kind="assignment" x="-263" y="-204">c = 0</label>
			<nail x="-272" y="-204"/>
			<nail x="-187" y="-204"/>
			<nail x="-187" y="-119"/>
			<nail x="-272" y="-119"/>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = MaximumDuration_State_Globally_Timed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] (Observer.Scope and Observer.c &gt;= $t1) imply $P
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/BoundedExistence_State_Between_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
bool R_holds, P_holds;
broadcast chan R_reached, Q_reached, P_reached, P_left;
int n_;</declaration>
	<template>
		<name x="5" y="5">BoundedExistence_State_Between_Untimed</name>
		<declaration>// Place local declarations here.
int counter = 0;</declaration>
		<location id="id0" x="-748" y="-340">
			<committed/>
		</location>
		<location id="id1" x="-875" y="-340">
			<name x="-909" y="-331">INIT</name>
		</location>
		<location id="id2" x="178" y="-467">
			<name x="195" y="-475">ERROR</name>
		</location>
		<location id="id3" x="59" y="-467">
		</location>
		<location id="id4" x="-93" y="-467">
			<committed/>
		</location>
		<location id="id5" x="-476" y="-340">
			<committed/>
		</location>
		<location id="id6" x="-280" y="-467">
		</location>
		<location id="id7" x="-280" y="-340">
		</location>
		<location id="id8" x="-603" y="-340">
			<committed/>
		</location>
		<init ref="id1"/>
		<transition>
			<source ref="id0"/>
			<target ref="id1"/>
			<label kind="guard" x="-858" y="-416">R_holds == 1</label>
			<nail x="-748" y="-391"/>
			<nail x="-875" y="-391"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id8"/>
			<label kind="guard" x="-722" y="-365">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-857" y="-357">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-654" y="-535">R_reached?</label>
			<nail x="-280" y="-510"/>
			<nail x="-909" y="-510"/>
			<nail x="-909" y="-340"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-858" y="-323">R_reached?</label>
			<nail x="-280" y="-306"/>
			<nail x="-875" y="-306"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="76" y="-493">R_reached?</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="guard" x="-68" y="-493">counter &gt; n_</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id6"/>
			<label kind="guard" x="-246" y="-493">counter &lt;= n_</label>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-238" y="-374">P_reached?</label>
			<label kind="assignment" x="-255" y="-357">counter = counter+1</label>
			<nail x="-93" y="-340"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id6"/>
			<label kind="guard" x="-467" y="-484">P_holds == 1</label>
			<label kind="assignment" x="-467" y="-467">counter = counter+1</label>
			<nail x="-476" y="-467"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id7"/>
			<label kind="guard" x="-433" y="-365">P_holds == 0</label>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id5"/>
			<label kind="assignment" x="-586" y="-365">counter = 0</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id7"/>
			<label kind="synchronisation" x="-272" y="-425">P_left?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = BoundedExistence_State_Between_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] Observer.INIT imply not $Q
			</formula>
			<comment>
			</comment>
		</query>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/Precedence_State_Globally_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan S_reached, P_reached;</declaration>
	<template>
		<name x="5" y="5">Precedence_State_Globally_Untimed</name>
		<declaration>// Place local declarations here.
</declaration>
		<location id="id0" x="-926" y="-459">
			<name x="-926" y="-493">ERROR</name>
		</location>
		<location id="id1" x="-926" y="-561">
		</location>
		<location id="id2" x="-1096" y="-561">
		</location>
		<init ref="id2"/>
		<transition>
			<source ref="id2"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-1079" y="-476">P_reached?</label>
			<nail x="-1096" y="-459"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-1078" y="-578">S_reached?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Precedence_State_Globally_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/PrecedenceChain1N_State_After_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan Q_reached, P_reached, S_reached, T1_reached, T2_reached, T3_reached;
bool T1_holds, T2_holds, T3_holds, S_holds, P_holds;</declaration>
	<template>
		<name x="5" y="5">PrecedenceChain_State_After_Untimed</name>
		<declaration>// Place local declarations here.
bool Z_Flag = 0;
bool P_Flag = 0;
</declaration>
		<location id="id0" x="-2694" y="-493">
		</location>
		<location id="id1" x="-2439" y="-493">
			<committed/>
		</location>
		<location id="id2" x="-2558" y="-493">
			<committed/>
		</location>
		<location id="id3" x="-2125" y="-493">
			<committed/>
		</location>
		<location id="id4" x="-1929" y="-331">
			<committed/>
		</location>
		<location id="id5" x="-1929" y="-493">
			<name x="-1921" y="-527">INIT</name>
		</location>
		<location id="id6" x="-909" y="-493">
			<name x="-919" y="-527">END</name>
		</location>
		<location id="id7" x="-1037" y="-433">
		</location>
		<location id="id8" x="-1207" y="-493">
			<committed/>
		</location>
		<location id="id9" x="-1343" y="-433">
		</location>
		<location id="id10" x="-1521" y="-493">
			<committed/>
		</location>
		<location id="id11" x="-1648" y="-434">
		</location>
		<location id="id12" x="-1776" y="-493">
			<committed/>
		</location>
		<init ref="id0"/>
		<transition>
			<source ref="id3"/>
			<target ref="id12"/>
			<label kind="guard" x="-2107" y="-739">S_holds == 1</label>
			<nail x="-2124" y="-722"/>
			<nail x="-1776" y="-722"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id5"/>
			<label kind="guard" x="-2099" y="-510">S_holds == 0</label>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="guard" x="-2286" y="-459">T3_holds == 0</label>
			<nail x="-2405" y="-442"/>
			<nail x="-2142" y="-442"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="guard" x="-2286" y="-476">T2_holds == 0</label>
			<nail x="-2405" y="-459"/>
			<nail x="-2150" y="-459"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="guard" x="-2286" y="-493">T1_holds == 0</label>
			<nail x="-2397" y="-476"/>
			<nail x="-2150" y="-476"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id6"/>
			<label kind="guard" x="-2150" y="-280">S_holds == 1 &amp;&amp;
T1_holds == 1 &amp;&amp;
T2_holds == 1 &amp;&amp;
T3_holds == 1</label>
			<nail x="-2438" y="-212"/>
			<nail x="-875" y="-212"/>
			<nail x="-875" y="-476"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id3"/>
			<label kind="guard" x="-2286" y="-510">S_holds == 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="guard" x="-2541" y="-552">P_holds == 0</label>
			<nail x="-2558" y="-535"/>
			<nail x="-2439" y="-535"/>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="guard" x="-2541" y="-510">P_holds == 1</label>
			<label kind="assignment" x="-2540" y="-493">P_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-2676" y="-510">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id5"/>
			<nail x="-1946" y="-476"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-1929" y="-429">P_reached?</label>
			<label kind="assignment" x="-1929" y="-412">P_Flag = 1</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id12"/>
			<label kind="synchronisation" x="-1895" y="-510">S_reached?</label>
		</transition>
		<transition>
			<source ref="id11"/>
			<target ref="id10"/>
			<label kind="synchronisation" x="-1630" y="-450">T1_reached?</label>
			<nail x="-1521" y="-433"/>
		</transition>
		<transition>
			<source ref="id12"/>
			<target ref="id11"/>
			<label kind="guard" x="-1768" y="-450">T1_holds == 0</label>
			<nail x="-1776" y="-433"/>
		</transition>
		<transition>
			<source ref="id7"/>
			<target ref="id6"/>
			<label kind="synchronisation" x="-1019" y="-450">T3_reached?</label>
			<nail x="-909" y="-433"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id7"/>
			<label kind="guard" x="-1182" y="-450">T3_holds == 0</label>
			<nail x="-1190" y="-433"/>
		</transition>
		<transition>
			<source ref="id9"/>
			<target ref="id8"/>
			<label kind="synchronisation" x="-1325" y="-450">T2_reached?</label>
			<nail x="-1207" y="-433"/>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id9"/>
			<label kind="guard" x="-1487" y="-450">T2_holds == 0</label>
			<nail x="-1504" y="-433"/>
		</transition>
		<transition>
			<source ref="id8"/>
			<target ref="id6"/>
			<label kind="guard" x="-1182" y="-510">T3_holds == 1</label>
		</transition>
		<transition>
			<source ref="id10"/>
			<target ref="id8"/>
			<label kind="guard" x="-1487" y="-510">T2_holds == 1</label>
		</transition>
		<transition>
			<source ref="id12"/>
			<target ref="id10"/>
			<label kind="guard" x="-1759" y="-510">T1_holds == 1</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Process = PrecedenceChain_State_After_Untimed();
// List one or more processes to be composed into a system.
system Process;
    </system>
	<queries>
		<query>
			<formula>START --&gt; GOAL
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/observer_templates/Until_State_Between_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan R_reached, P_left, Q_reached, S_reached;
bool R_holds, P_holds;</declaration>
	<template>
		<name x="5" y="5">Until_State_Between_Untimed</name>
		<declaration>// Place local declarations here.</declaration>
		<location id="id0" x="-960" y="-1428">
			<name x="-970" y="-1462">ERROR</name>
		</location>
		<location id="id1" x="-1504" y="-1428">
			<committed/>
		</location>
		<location id="id2" x="-1657" y="-1428">
			<name x="-1667" y="-1462">INIT</name>
		</location>
		<location id="id3" x="-1359" y="-1360">
		</location>
		<location id="id4" x="-1079" y="-1428">
		</location>
		<location id="id5" x="-1198" y="-1428">
			<name x="-1208" y="-1462">O1</name>
		</location>
		<location id="id6" x="-1351" y="-1428">
			<name x="-1368" y="-1411">O2</name>
			<committed/>
		</location>
		<init ref="id2"/>
		<transition>
			<source ref="id4"/>
			<target ref="id0"/>
			<label kind="synchronisation" x="-1061" y="-1445">R_reached?</label>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-1639" y="-1377">R_reached?</label>
			<nail x="-1657" y="-1360"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id2"/>
			<label kind="guard" x="-1631" y="-1420">R_holds == 1</label>
			<nail x="-1521" y="-1403"/>
			<nail x="-1640" y="-1403"/>
		</transition>
		<transition>
			<source ref="id1"/>
			<target ref="id6"/>
			<label kind="guard" x="-1478" y="-1445">R_holds == 0</label>
		</transition>
		<transition>
			<source ref="id2"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-1639" y="-1445">Q_reached?</label>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-1325" y="-1377">S_reached?</label>
			<nail x="-1198" y="-1360"/>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id4"/>
			<label kind="guard" x="-1325" y="-1505">P_holds == 0</label>
			<nail x="-1351" y="-1488"/>
			<nail x="-1079" y="-1488"/>
		</transition>
		<transition>
			<source ref="id5"/>
			<target ref="id4"/>
			<label kind="synchronisation" x="-1180" y="-1445">P_left?</label>
		</transition>
		<transition>
			<source ref="id6"/>
			<target ref="id5"/>
			<label kind="guard" x="-1325" y="-1445">P_holds == 1</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Until_State_Between_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>

=== hub-se/PSP-UPPAAL/Tool/observer_templates/Absence_State_Before_Untimed.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nta PUBLIC "-//Uppaal Team//DTD Flat System 1.1//EN" "flat-1_1.dtd">
<nta>
	<declaration>// Place global declarations here.
broadcast chan P_reached, R_reached;
bool R_holds, P_holds;
bool nxtCmt = 1;</declaration>
	<template>
		<name x="5" y="5">Absence_State_Before_Untimed</name>
		<declaration>// Place local declarations here.</declaration>
		<location id="id0" x="-620" y="-93">
			<name x="-671" y="-119">INIT</name>
			<committed/>
		</location>
		<location id="id1" x="-170" y="-42">
			<name x="-144" y="-51">SCOPECLOSED</name>
		</location>
		<location id="id2" x="-17" y="-93">
			<name x="-34" y="-76">ERROR</name>
		</location>
		<location id="id3" x="-161" y="-93">
		</location>
		<location id="id4" x="-314" y="-93">
		</location>
		<init ref="id0"/>
		<transition>
			<source ref="id0"/>
			<target ref="id1"/>
			<label kind="guard" x="-578" y="-34">R_holds == 1</label>
			<label kind="assignment" x="-578" y="-8">nxtCmt=0</label>
			<nail x="-620" y="-8"/>
			<nail x="-170" y="-8"/>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id4"/>
			<label kind="guard" x="-578" y="-119">R_holds == 0 &amp;&amp; P_holds == 0</label>
			<label kind="assignment" x="-578" y="-93">nxtCmt=0</label>
		</transition>
		<transition>
			<source ref="id0"/>
			<target ref="id3"/>
			<label kind="guard" x="-578" y="-170">R_holds == 0 &amp;&amp; P_holds == 1</label>
			<label kind="assignment" x="-578" y="-144">nxtCmt=0</label>
			<nail x="-620" y="-144"/>
			<nail x="-161" y="-144"/>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id1"/>
			<label kind="synchronisation" x="-280" y="-68">R_reached?</label>
			<nail x="-314" y="-42"/>
		</transition>
		<transition>
			<source ref="id3"/>
			<target ref="id2"/>
			<label kind="synchronisation" x="-127" y="-119">R_reached?</label>
		</transition>
		<transition>
			<source ref="id4"/>
			<target ref="id3"/>
			<label kind="synchronisation" x="-280" y="-119">P_reached?</label>
		</transition>
	</template>
	<system>// Place template instantiations here.
Observer = Absence_State_Before_Untimed();
// List one or more processes to be composed into a system.
system Observer;
    </system>
	<queries>
		<query>
			<formula>A[] not Observer.ERROR
			</formula>
			<comment>
			</comment>
		</query>
	</queries>
</nta>
